TMCFG_KERN_ARCH := mips
TMCFG_TC_PFX := $(OCTEON_ROOT)/tools/bin/mips64-octeon-linux-gnu-
TMCFG_KERN_DIR := $(OCTEON_ROOT)/linux/kernel/linux


TMCFG_E_EXTRA_CFLAGS :=  -I$(TDTS_KMOD_DIR)/../../include
TMCFG_E_CORE_USE_KBUILD := y
TMCFG_DBG_VERBOSE_CC_MSG := y

